### ISSUE TITLE
Road Alignment: Metro Manila

### ISSUE THREAD

**Issue by govvin** [mapamore/kaart-ph#12]
>![image](https://user-images.githubusercontent.com/5821688/36338398-cbf44c8a-13e8-11e8-927a-acf73b64d106.png)
> Positional accuracy: light blue (<7m), yellow (7-10m), red (>10m)

## Issue
Based on Kaart GIS analysis, the Philippine road network data has positional errors (~3-17m) when compared to existing track logs (OpenStreetMap and Strava), and may also include incorrect topology that does not match aerial imagery.

### To Do
- [x] contact the local [OSM mailing list](https://lists.openstreetmap.org/listinfo/talk-ph) and present the proposed road realignment strategy, for suggestions and feedback.
- [x] set-up a tasking manager [project](https://tasks.hotosm.org/project/4180)
- [x] amend project, based on community feedback, if any. make the task public ?
- [x] @GOwin to run task, monitor issues, and coordinate closely with @ralleon

## Proposed road realignment strategy
  0.  Where available, use Bing as baseline, but verify its accuracy by comparing with SatNav (OSM track logs, Strava heatmaps) data.  Same applies for any other available aerial imagery (e.g. Mapbox, Digital Globe Digital, ESRI World Imagery).
  0. Publish offsets to the [Imagery Offsets Database (IODb)](http://offsets.textual.ru/map). Deprecate IODb entries, when necessary.
  0. For grid networks, attempt to offset data to match imagery. If not successful or practical, retrace the area.
  0. Realign all other roads, correct topology errors, and mark as finished.

### Coverage
- Metro Manila, Philippines

### Guidelines
- The contributors will follow [OpenStreetMap](http://wiki.openstreetmap.org/wiki/Highways), regional, and [national](https://wiki.openstreetmap.org/wiki/Philippines/) practices, along with Kaart Data Team [guidelines](https://wiki.openstreetmap.org/wiki/Kaart#Data_Team_Guidelines), as appropriate.

### Data Sources
- Public imagery (Bing, MapBox, Digital Globe, ESRI World) 
- Public traces (OSM track logs, Strava heatmap)
- Street-level imagery (Mapillary, OpenStreetCam, Pic4Carto)
- GIS imagery analysis by Kaart

## Validation and Error Detection
The contributors will visually check for errors together with using [JOSM validation warnings](http://wiki.openstreetmap.org/wiki/JOSM/Validator) prior to committing the changeset.

In addition, the contributors will review their work in accordance with the task guidelines including the [OSM Wiki](http://wiki.openstreetmap.org/wiki/OSM_Tasking_Manager/Validating_data) and [LearnOSM](http://learnosm.org/en/coordination/review/) validation conventions.

### Contributors
The project is limited to OpenStreetMap contributors adept in JOSM, with advanced mapping skills.

**Comment by govvin** [comment]
Example of [task](https://tasks.hotosm.org/project/4180?task=1540) with a mis-aligned bridge, as seen from aerial imagery, and detected by data analysis.

![image](https://user-images.githubusercontent.com/5821688/36466272-30f529fa-1714-11e8-8beb-4615c5eb2079.png)

**Comment by govvin** [comment]
Data analysis don't always catch mis-alignments, like [this](https://tasks.hotosm.org/project/4180?task=2840) one.

![image](https://user-images.githubusercontent.com/5821688/36469866-b9acd78e-1723-11e8-9e31-ff967d643d81.png)

**Comment by ralleon** [comment]
![metromanila bing-strava verified accurate alignments](https://user-images.githubusercontent.com/625238/36483686-cce7ffee-1751-11e8-84ee-2f0d23c3df21.jpg)

I tried to find fault/misaligned imagery with extensive observations in this area, but Bing (though cloudy in some parts) is very well aligned with Strava within this boxed imagery. I cannot find any significant anomaly. Good works on Bing (in this boxed area), unlike Digital Globe which have many distorted/stretched images found.

Boundary: Generally from upper Quezon City/Kalookan (on the North); On the East up to Batasang Pambansa in Quezon City, left of Marikina River up down to Taguig (lower righ corner), but up to NAIA runway only on the South.

This will save a lot of time on workflow (in fact I don't recommend aligning and interpreting partial GPS data, nor individually interpret Strava for localized alignment). I HIGHLY RECOMMEND that we should just simply align all OSM data exclusively on Bing within the said boundary, as well as align all other imagery (Mapbox, Digital Globe, ESRI on Bing) for the latest map feature update in the area. 

The effort on this particular project should focus on establishing accurate offsets on IODb for Mapbox, Digital Globe, ESRI referenced to Bing (on its default Zero,Zero offset) for ease of tracing and realigning streets and adding new roads.

**Comment by ralleon** [comment]
![image](https://user-images.githubusercontent.com/625238/36484805-5c677868-1755-11e8-9ce4-24db48081fa8.png)

**Comment by govvin** [comment]
Determining offsets, and recording them on IODb is a secondary goal @ralleon

**Comment by govvin** [comment]
Determining offsets, and recording them on IODb is a secondary goal @ralleon

**Comment by govvin** [comment]
Take advantage of AI with Strava's [iD Slide](https://labs.strava.com/slide/), which looks very helpful for major roads, but must be used with caution: 
![image](https://user-images.githubusercontent.com/5821688/36617701-7fb6ae22-1923-11e8-912b-cecb24c7a8bd.png)

- Check intersections
- Only use on roads with very high heatmap values

Use the following for the Custom URL Utilsplugin2: `https://strava.github.io/iD/#background=Bing&map=19.00/{#lon}/{#lat}`

**Comment by govvin** [comment]
This issue was moved to KaartGroup/Philippines#9

**Comment by govvin** [comment]
[Grab's OpenStreetMap data team](https://github.com/GRABOSM/Grab-Data/) has been in touch, and is co-ordinating their effort to identifying missing roads, and improving road geometry in Metro Manila. They've also adopted the use of the [Imagery Offset Database](http://offsets.textual.ru/map) to maintain mapping consistency across the mapping community.
